# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    continueOnError: false
    inputs:
      version: '7.x'

  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    continueOnError: false
    inputs:
      command: restore

  - task: DotNetCoreCLI@2
    displayName: '.NET build $(buildConfiguration)'
    continueOnError: false
    inputs:
      command: 'build'
      projects: 'Application/Application.csproj'
      arguments: '--configuration $(buildConfiguration)'
      
  - task: DotNetCoreCLI@2
    displayName: 'Publish Artifacts'
    continueOnError: false
    inputs:
      command: publish
      projects: 'Application/Application.csproj'
      publishWebProjects: True
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: True

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'HorizonSite'

  # - task: AzureRmWebAppDeployment@4
  #   continueOnError: false
  #   displayName: 'Deploy to Azure'
  #   inputs:
  #     ConnectionType: 'AzureRM'
  #     azureSubscription: 'Pago pelo Uso (cbb3358e-dd46-4cb3-afef-3aa600faa39a)'
  #     appType: 'webAppLinux'
  #     WebAppName: 'horizon-tour-api'
  #     packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
